### ISSUE TITLE
No such file or directory: './assets/maps//parts/'

### ISSUE THREAD

**Issue by antoninhrlt** [PainOchoco/DashRun#1]
I've downloaded the repository by running a `git clone` command. Then, I tried to run the project with the python interpreter: `python3 main.py`, but an error has been returned: 
```
pygame 2.1.0 (SDL 2.0.16, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/anton/DashRun/main.py", line 226, in <module>
    game.new()
  File "/home/anton/DashRun/main.py", line 62, in new
    self.world.generate()
  File "/home/anton/DashRun/components/world.py", line 26, in generate
    self.map_files = os.listdir(self.path + "/parts/")
FileNotFoundError: [Errno 2] No such file or directory: './assets/maps//parts/'
```
There is nothing in the "assets/maps/" folder that looks like "parts":
![Screenshot from 2021-12-23 19-29-12](https://user-images.githubusercontent.com/66388237/147279312-c2570cf8-fac3-4b33-837b-f5f2f18ea0e8.png)

(Other thing: Your latest release as .zip file is different than this current repository, you should make an update)
(Other other thing: You should remove the character: "/" at begin of the "/parts" path, because you have two slash here)

**Comment by antoninhrlt** [comment]
After fixing that, I will make a pull request for some changes that can be added to the project (little things, but important)
